# Generated by Django 5.2.13 on 2026-04-17 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('queries_total', models.IntegerField(default=0)),
                ('queries_done', models.IntegerField(default=0)),
                ('pages_fetched', models.IntegerField(default=0)),
                ('people_unique', models.IntegerField(default=0)),
                ('leads_final', models.IntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=16)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=80)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('emails', models.JSONField(blank=True, default=list)),
                ('email_candidates', models.JSONField(blank=True, default=list)),
                ('phones', models.JSONField(blank=True, default=list)),
                ('linkedin', models.URLField(blank=True, default='', max_length=500)),
                ('fund_size', models.CharField(blank=True, default='', max_length=80)),
                ('fund_close_step', models.CharField(blank=True, default='', max_length=40)),
                ('recency_months', models.FloatField(blank=True, null=True)),
                ('lead_score', models.FloatField(db_index=True, default=0.0)),
                ('source', models.CharField(default='', max_length=16)),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('source_title', models.CharField(blank=True, default='', max_length=500)),
                ('evidence', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='hq.scraperun')),
            ],
            options={
                'ordering': ['-lead_score'],
            },
        ),
    ]
