# Generated by Django 5.2.13 on 2026-04-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0002_task_comment_tasklike_taskvote_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=200)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('intent', models.CharField(choices=[('info', 'Information'), ('engagement', 'Engagement'), ('partnership', 'Partnership'), ('press', 'Press')], default='info', max_length=20)),
                ('message', models.TextField(max_length=5000)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['handled', 'created_at'], name='hq_contactm_handled_2fd884_idx')],
            },
        ),
    ]
