# Generated by Django 5.2.13 on 2026-04-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='company_description',
            field=models.TextField(blank=True, default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='lead',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='llm_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='llm_score_reasoning',
            field=models.TextField(blank=True, default='', max_length=800),
        ),
        migrations.AddField(
            model_name='lead',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='seniority',
            field=models.CharField(blank=True, choices=[('founder', 'Founder'), ('exec', 'Executive'), ('senior', 'Senior'), ('mid', 'Mid'), ('junior', 'Junior')], default='', max_length=16),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['country', '-lead_score'], name='hq_lead_country_d6becc_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-created_at'], name='hq_lead_created_583a25_idx'),
        ),
    ]
